image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://docker:2375"

stages:
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

deploy:production:
  image: ruby:latest
  stage: deploy
  only:
    - tags
  script:
    - git checkout master
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=devnews-production --api-key=$HEROKU_TOKEN

deploy:staging:
  image: ruby:latest
  stage: deploy
  only:
    - master
  script:
    - git checkout master
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=devnews-staging --api-key=$HEROKU_TOKEN

deploy:dev:
  image: ruby:latest
  stage: deploy
  only:
    - develop
  script:
    - git checkout develop
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=devnews-dev --api-key=$HEROKU_TOKEN

after_script:
  - echo "End CI"