image: openjdk:11

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - ./gradlew clean build --stacktrace
    - docker build -f Dockerfile --iidfile imageid.txt -t registry.heroku.com/drivefocus-services/backend .

deploy:
  stage: deploy
  script:
    - docker login -u _ -p $HEROKU_TOKEN registry.heroku.com
    - docker push registry.heroku.com/drivefocus-services/backend
    - apk add --no-cache curl
    - echo "Docker Image ID is $(cat imageid.txt)"

after_script:
  - echo "End CI"