image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://docker:2375"

stages:
  - build
  - package
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  image: openjdk:11
  stage: build
  artifacts:
    paths:
    - build/libs/*.jar
  script:
    - ./gradlew clean build

package:
  stage: package
  dependencies:
    - build
  script:
    - docker build -f Dockerfile --iidfile imageid.txt -t registry.heroku.com/drivefocus-services/backend .

deploy:
  stage: deploy
  dependencies:
    - package
  script:
    - docker login -u _ -p $HEROKU_TOKEN registry.heroku.com
    - docker push registry.heroku.com/drivefocus-services/backend
    - apk add --no-cache curl
    - echo "Docker Image ID is $(cat imageid.txt)"

after_script:
  - echo "End CI"