image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://docker:2375"

stages:
  - build
  - package
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
  - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
  - apt-get update
  - apt-get install -y heroku-toolbelt
  - gem install dpl

build:
  image: openjdk:11
  stage: build
  only:
    - master
  artifacts:
    paths:
      - build/libs/*.jar
  script:
    - git checkout master
    - ./gradlew clean build

build:dev:
  image: openjdk:11
  stage: build
  only:
    - develop
  artifacts:
    paths:
      - build/libs/*.jar
  script:
    - git checkout develop
    - ./gradlew clean build

package:
  stage: package
  dependencies:
    - build
    - build:dev
  script:
    - docker login -u artsem.kniazeu@gmail.com -p $GITLAB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/devnews/devnews-service .
    - docker push registry.gitlab.com/devnews/devnews-service


deploy:
  stage: deploy
  only:
    - master
  dependencies:
    - package
  script:
    - docker login -u artsem.kniazeu@gmail.com -p $GITLAB_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/devnews/devnews-service
    - docker tag registry.gitlab.com/devnews-dev/devnews-service registry.heroku.com/devnews-staging/web
    - dpl --provider=heroku --app=devnews-staging --api-key=$HEROKU_TOKEN
    - heroku container:login
    - heroku container:push web -a "devnews-staging"
    - heroku container:release web -a "devnews-staging"

deploy:dev:
  stage: deploy
  only:
    - develop
  dependencies:
    - package
  script:
    - docker login -u artsem.kniazeu@gmail.com -p $GITLAB_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/devnews/devnews-service
    - docker tag registry.gitlab.com/devnews/devnews-service registry.heroku.com/devnews-dev/web
    - dpl --provider=heroku --app=devnews-dev --api-key=$HEROKU_TOKEN
    - heroku container:login
    - heroku container:push web -a "devnews-dev"
    - heroku container:release web -a "devnews-dev"

after_script:
  - echo "End CI"