image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://docker:2375"

stages:
  - build
  - package
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  image: openjdk:11
  stage: build
  artifacts:
    paths:
    - build/libs/*.jar
  script:
    - ./gradlew clean build

package:
  stage: package
  dependencies:
    - build
  script:
    - docker login -u artsem.kniazeu@gmail.com -p $GITLAB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/devnews/devnews-service .
    - docker push registry.gitlab.com/devnews/devnews-service

deploy:
  stage: deploy
  dependencies:
    - package
  script:
    - docker login -u artsem.kniazeu@gmail.com -p $GITLAB_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/devnews/devnews-service
    - docker logout
    - docker login -u artsem.kniazeu@gmail.com -p $HEROKU_TOKEN registry.heroku.com
    - docker push registry.gitlab.com/devnews/devnews-service
    - apk add --no-cache curl

after_script:
  - echo "End CI"