version: "3.7"
services:

  postgres-db:
    image: mdillon/postgis:10-alpine
    container_name: devnews-postgres
    environment:
      - POSTGRES_USER=devnews
      - POSTGRES_PASSWORD=devnews
      - POSTGRES_DB=devnews_db
    ports:
      - "5433:5432"