---
app:
  jwt:
    base64-secret: "${APP_JWT_BASE64_SECRET:}"
    access-token-validity: "${APP_JWT_ACCESS_TOKEN_VALIDITY}"
    refresh-token-validity: "${APP_JWT_REFRESH_TOKEN_VALIDITY}"
  google:
    storage:
      image-bucket: "${APP_GOOGLE_CLOUD_STORAGE_IMAGE_BUCKET}"
      video-bucket: "${APP_GOOGLE_CLOUD_STORAGE_VIDEO_BUCKET}"
      key: "${APP_GOOGLE_CLOUD_STORAGE_KEY}"
  twilio:
    account-sid: "${APP_TWILIO_ACCOUNT_SID}"
    auth-token: "${APP_TWILIO_AUTH_TOKEN}"
    service-sid: "${APP_TWILIO_SERVICE_SID}"
  urls:
    web-url: "${APP_URLS_WEB_URL}"
    confirm-url: "${APP_URLS_WEB_URL}/activate"
    email-confirm-url: "${APP_URLS_WEB_URL}/email/activate"
    reset-url: "${APP_URLS_WEB_URL}/reset"
  mail:
    from: "${APP_MAIL_FROM}"
    replyTo: "${APP_URLS_REPLY_TO}"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${SPRING_DATASOURCE_URL:}"
    username: "${SPRING_DATASOURCE_USERNAME:}"
    password: "${SPRING_DATASOURCE_PASSWORD:}"

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  jackson:
    default-property-inclusion: non_null

  mustache:
    cache: true
    suffix: ""

server:
  port: "${PORT:8080}"

---
logging:
  level:
    org.hibernate.ejb.HibernatePersistence: DEBUG
    org.hibernate: DEBUG
    org.postgresql.jdbc: DEBUG
---

spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 1MB
  datasource:

    driver-class-name: org.postgresql.Driver
    username: devnews
    password: devnews
    url: jdbc:postgresql://localhost:5433/devnews_db
    tomcat:
      connection-properties: stringtype=unspecified

  flyway:
    baseline-on-migrate: true
  mail:
    host: "localhost"
    port: "1025"
    username: "devnews"
    password: "devnews"

---

---
spring:
  profiles: test
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 1MB
  flyway:
    baseline-on-migrate: true

---

app:
  jwt:
    base64-secret: "dvkfGCq2G00TFJ3j+4UDS+CPwAVLkLziJXlXUvNy2jr0NkIH4QPtfXOLpHK1G++RixsyY5CX6BRh82lZySF4Xg=="
    access-token-validity: "36000" # 1 hour in seconds
    refresh-token-validity: "2592000" # 30 days in seconds

  google:
    storage:
      image-bucket: "devnews-image-bucket"
      video-bucket: "devnews-video-bucket"
      key: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZGV2bmV3cy0yNTcxMjEiLAogICJwcml2YXRlX2tleV9pZCI6ICI4ZTNiNGFhMzRmN2VjODhiZDIyZDhhNWU3ZjIwYTBlMjVhOGZiMzBiIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdndJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLa3dnZ1NsQWdFQUFvSUJBUUM4YXc4TlVsTkZ3VU5VXG5aeVdReHJKbUlwRWxaL0cwa3ZLUnNHRnNCT1A0aHVrdFRjYUZWMG96eDlYTm0vQ3MzeE9sMU5tdExtZGNKSEdSXG5Xc2JrSXFwT2RPUVZXODVGZFpPR1RzUE1SanpCZ1M0M2p2cXNIRzFDeHBxdlVjR1lWekdKaUFIVE55OEg5L1JuXG5BcituTU9aWEIwd21YMlYrblZlOWZQaFZ2WHo0dEM4WXVtSnB6QjROMzYxTFJFaVIrRjZseElJZGNoRThZYWxjXG5icm81U05VVTEvcnVNNmhlMk5kdmtESU4zeEV4Vldmek9LOFcyOUpxVERCVTdZTWVoRkNvakhYT0d1TFB1YVlaXG42ekg3cGtrQmdydDJvWXcrQ2x6eW90ZVJReXF5TWtsMkJ6WnMxbElBZTFYWW1WZkE5L2tiNk15NWdRNStwajdZXG5xTmxabzc2eEFnTUJBQUVDZ2dFQUZoeTlXenVnWkxVUjdRZWU1Nzc5NUZFbHRoMWRCeXRndHRyYmtCVUIyU0tpXG5IbXc4Z2wwVWF2L0dsbmI0MTV6bGZpWjg5bDlXQjRFS1ovdmVrQnNHWUNkRk5rRjhNM2doUEZlbGtHVmt6M1BVXG40L1hPY3VEeUxLNUlySThjZUgreEkxb1lGcnpvOHRjMWNscG0raHpaeDNobWhqRlhaTFRiL1hPN1pEcVUvazNaXG5mWm1NZjdRNi9mTVErenJRQmhMcXgrUklNTm1hTEE4L2FjLzNOTjFzSE16RWQ0RlMvcU5uOFMySmNzWFFCbDA5XG5UeWdOTi9nS25CV1NPdTh3QTBRc2pSRnR3WHNlU1ZSNDlNenhRRFE2Rk1YVEcwbGlYZnZOaHB1QkhwdjlxKzlEXG5YWDJ0dWpKUVdoNTdRU2M1UnNTMDlITGNYTlMrKzgyNnBNWC9Xb1NNelFLQmdRRHBNZ0lJTDQ4dzFQQ2FiMTA0XG5mS0N2eEFYc0ZFWmNtR0VLc09FNE44UG9ROEs3ZW56dWJZc3cwbW1WMEcvODlkZHZaL2VBUkJjRWxHT1FWbnE3XG4yMkd4N0RCZVhINjlEQzJNVVBKSEV0OWtHd1J6NXhjUHFsc2JiZDBoMElGNGpMZHhWc0djcDEreDVyWDg1bG9XXG4vV3BUbXIyNXkwSW5oVSs4Yk5vc2RFNFBuUUtCZ1FETzJCQzJIaWVpZDdMRnk1dTdQSWRjSEFQdWh0dzBaZW1uXG5nM1VMQk9zVm9nT29DaXJCb2ZDR3QxUndZSkxnQU1UdnB2R1dSV2FIKzlTWUJhZytWTDZ3YjJQTFpEdldpQm5JXG5uSXlUR1lYZkhmK2FPa0lEUGd2SlorbmYycW84ei90MlpnUk1JWUt3ZnR5WHRVdWcvV2NIYWc3cHhKUUFIRW00XG51NitFUytWaEpRS0JnUUNWbWh0cm5QZEQ0SmdxdTE4V3FmMThSVWwzVnRwODlOVHN3dVQ1NSt5cXlTM1lrSkF0XG5kZUZpQk5ydjNiUzZtQTBKejYwY2dKSXp3ZTdOM20wR3I0dFJWYkVDR0Z6R2MxV1ZPeWp6Sjh4Z3NHUis1cllJXG51c1dRSno5Q1BqMlJWTlVxeFBtWXdsZkdEYmlhOGp6Qm12bm5nTkpPcTNOWlgxRDBGUEV5cTdxWWtRS0JnUUN0XG5Zc0RmYUhlZzRPV2ltQUo2K1VvZUUvM1h2SVJxQitQTTM0MEZKNkpJQi84NHBRMGlNelVFT0RrMzJqeEVPV0RiXG40djB3RWd6WWdHaTg1a0VadnIvNTllV1pZUFFuNlA1MEE0Wnk2RG9ueFdXMVNwQjdWMDlhRFJrbTVJMC9YTGhWXG5qejZhOHB3eWhxVXpKbTIzRGJPSHE0ZkV2VnV5bkFQUUxzUDZDZ1RGWVFLQmdRRFp5SkZFK1N5SGEybWhXUGt3XG5IRkJYZG9DcWFzMnJ4RHZleDRvcUtMeUI2VWkxMG1GcWJpR2s1VE8wY0pSZVMwV0FSK1JuOU9md24wazFNcFk2XG56RkpSc1RobFhiOHNYa3NzSTZkd2wwNmpiRDN5VUVwZXJibERrSTlQQjZXZG9zK0JXQWYxaTY1ck5QNFFCUWZqXG5tTHR1QTI3Q01memFCU1ZZT1JmUi85TWlOZz09XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiODQzMzAwMzM1MzgxLWNvbXB1dGVAZGV2ZWxvcGVyLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTE4Mjk1MzM3Mjk3NzAzOTMyMTA4IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS84NDMzMDAzMzUzODEtY29tcHV0ZSU0MGRldmVsb3Blci5nc2VydmljZWFjY291bnQuY29tIgp9Cg=="

  twilio:
    account-sid: "AC312cd5f34b97488f8d446679f959ce4b"
    auth-token: "cd857cc6816cebb42e1e00d61a0c040f"
    service-sid: "VAfe9e384a1c0bf3d1969de2e56e01b1a2"

  urls:
    web-url: "http://localhost:4000"
    confirm-url: "http://localhost:4000/activate"
    email-confirm-url: "http://localhost:4000/email/activate"
    reset-url: "http://localhost:4000/reset"

  mail:
    from: "no-reply@example.com"
    replyTo: "info@example.com"